export const $=s=>document.querySelector(s);
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const money=n=>'$'+Number(n||0).toLocaleString('en-US',{maximumFractionDigits:2});
export const date=s=>new Date(s).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'});
export const labels={received:'Reçue',confirmed:'Confirmée',preparing:'En préparation',ready:'Prête',out_for_delivery:'En livraison',completed:'Terminée',cancelled:'Annulée',reviewing:'À l’étude',sourcing:'Recherche en cours',pending:'À régler',paid:'Réglé',refunded:'Remboursé',order:'Commande',sell:'Proposition',source:'Recherche',offer:'Ancienne offre'};
export const safeURL=s=>{try{const u=new URL(s,location.href);return ['http:','https:'].includes(u.protocol)?esc(u.href):'';}catch{return '';}};
export const field=(label,name,type='text',extra='',value='')=>`<label class="field">${label}<input name="${name}" type="${type}" ${extra} value="${esc(value)}"></label>`;
export function toast(s){let el=$('#toast');if(!el){el=document.createElement('div');el.id='toast';el.setAttribute('role','status');document.body.append(el);}el.textContent=s;el.classList.add('visible');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('visible'),3500);}
export function receipt(r){return `<div class="receipt"><div class="eyebrow">SIDEHUSTLE / ${esc(labels[r.type])}</div><h2>${esc(r.reference)}</h2><p>${r.name?esc(r.name)+' · ':''}${date(r.created_at)}</p><span class="status ${r.status}">${esc(labels[r.status])}</span>${r.type==='order'?`<div class="receipt-items">${r.items.map(i=>`<div><span>${i.quantity} × ${esc(i.name)} ${esc(i.size||'')}</span><strong>${money(i.price*i.quantity)}</strong></div>`).join('')}<div><span>Livraison</span><strong>${money(r.delivery_fee)}</strong></div><div class="receipt-total"><span>Total</span><strong>${money(r.total)}</strong></div></div><p>${esc(labels[r.payment])} · ${r.fulfillment==='delivery'?'Livraison'+(r.address?' : '+esc(r.address):''):'Retrait au comptoir'}</p>`:`<p>${esc(r.details)}</p>${r.budget?`<p>Budget : ${money(r.budget)}</p>`:''}`}${r.delivery_slot?`<p><strong>Créneau :</strong> ${esc(r.delivery_slot)}</p>`:''}${r.public_note?`<div class="notice">${esc(r.public_note)}</div>`:''}</div>`;}
export function timeline(r){return `<ol class="timeline">${r.events.map((e,i)=>`<li class="${i===r.events.length-1?'current':''}"><div><strong>${esc(labels[e.status]||e.status)}</strong><time>${date(e.created_at)}</time></div>${e.note?`<p>${esc(e.note)}</p>`:''}</li>`).join('')}</ol>`;}
