import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;`);
await db.exec(await readFile('supabase/schema.sql','utf8'));
await db.exec(`insert into auth.users values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');insert into public.admins values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');insert into public.products(id,name,category,price,stock,image_url) values('11111111-1111-4111-8111-111111111111','Test sneaker','Sneakers',100,3,'https://example.com/test.jpg');insert into public.requests(reference,type,name,phone,status,total) values('SH-LEGACY','order','Legacy','5550000','new',100);`);
const migration=await readFile('supabase/migration-v2.sql','utf8');await db.exec(migration);await db.exec(migration);
const rpc=async(sql,args=[])=> (await db.query(sql,args)).rows[0];
const stock=async()=>Number((await rpc('select stock from products limit 1')).stock);
const payload={type:'order',name:'Client',phone:'5551111',details:'Private detail',fulfillment:'delivery',address:'Private address',delivery_slot:'21h',items:[{id:'11111111-1111-4111-8111-111111111111',quantity:2}],expected_total:200,idempotency_key:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'};
const submit=async p=>(await rpc('select checkout_v2($1::jsonb) as r',[JSON.stringify(p)])).r;
const first=await submit(payload);assert.equal(await stock(),1);const retry=await submit(payload);assert.equal(retry.reference,first.reference);assert.equal(await stock(),1);
await assert.rejects(submit({...payload,phone:'5552222',idempotency_key:'cccccccc-cccc-4ccc-8ccc-cccccccccccc'}),/STOCK_CHANGED/);assert.equal(await stock(),1);
await assert.rejects(submit({...payload,phone:'5552222',items:[{id:payload.items[0].id,quantity:1}],expected_total:1,idempotency_key:'cccccccc-cccc-4ccc-8ccc-cccccccccccc'}),/PRICE_CHANGED/);assert.equal(await stock(),1);
const tracked=(await rpc('select track_v2($1) as r',['5551111'])).r;assert.equal(tracked.length,1);for(const key of ['address','phone','name','internal_note','details'])assert.equal(key in tracked[0],false);
const id=(await rpc('select id from requests where reference=$1',[first.reference])).id;
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',false);`);
await assert.rejects(db.exec('update public.products set stock=100'),/permission denied/);
await db.query('select admin_update_request($1,$2,$3,$4,$5,$6)',[id,'cancelled','pending','Annulé','Secret','21h']);assert.equal(await stock(),3);
await db.query('select admin_update_request($1,$2,$3,$4,$5,$6)',[id,'cancelled','pending','Annulé','Secret','21h']);assert.equal(await stock(),3);
await assert.rejects(db.query('select admin_update_request($1,$2,$3,$4,$5,$6)',[id,'confirmed','pending','','','']),/TERMINAL/);
await db.exec('reset role');assert.equal((await rpc("select status,reserved from requests where reference='SH-LEGACY'")).reserved,false);
const fresh=await submit({...payload,phone:'5553333',idempotency_key:'dddddddd-dddd-4ddd-8ddd-dddddddddddd'});
const freshId=(await rpc('select id from requests where reference=$1',[fresh.reference])).id;
await db.exec('set role authenticated');
await assert.rejects(db.query('select admin_update_request($1,$2,$3,$4,$5,$6)',[freshId,'completed','pending','','','']),/BAD_TRANSITION/);
for(const st of ['confirmed','preparing','ready','out_for_delivery'])await db.query('select admin_update_request($1,$2,$3,$4,$5,$6)',[freshId,st,'pending','','','']);
await assert.rejects(db.query('select admin_update_request($1,$2,$3,$4,$5,$6)',[freshId,'completed','pending','','','']),/PAYMENT/);
await db.query('select admin_update_request($1,$2,$3,$4,$5,$6)',[freshId,'completed','paid','','','']);assert.equal(await stock(),1);
const product={id:payload.items[0].id,name:'Test',category:'Sneakers',price:100,stock:10,expected_stock:3,condition:'Bon',description:'',image_url:'https://example.com/a.jpg',brand:'',size:'',color:'',sku:'',images:[],featured:false,archived:false};
await assert.rejects(db.query('select admin_save_product($1::jsonb)',[JSON.stringify(product)]),/STOCK_CONFLICT/);
await db.query('select admin_save_product($1::jsonb)',[JSON.stringify({...product,expected_stock:1})]);assert.equal(await stock(),10);
await db.exec("select set_config('request.jwt.claim.sub','eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',false)");
await assert.rejects(db.query('select admin_save_product($1::jsonb)',[JSON.stringify(product)]),/FORBIDDEN/);
assert.equal((await db.query('select * from requests')).rows.length,0);
await db.exec('reset role;set role anon');await assert.rejects(db.exec('select * from requests'),/permission denied/);await assert.rejects(db.query('select track_v2($1)',['5551111']),/permission denied/);
await db.close();console.log('PASS: V1 migration x2, stock reservation, idempotency, oversell rejection, price validation, phone-only safe projection, cancellation exactly once, state transitions, payment gate, optimistic stock conflict, admin auth and RLS.');
