import {createHash} from 'node:crypto';
export const errors={RATE_LIMIT:[429,'Trop de demandes. Réessayez dans une minute.'],STOCK_CHANGED:[409,'Une pièce n’est plus disponible dans cette quantité. Actualisez le stock.'],PRICE_CHANGED:[409,'Le prix ou les frais ont changé. Actualisez votre panier avant de confirmer.'],SHOP_CLOSED:[409,'Le comptoir a temporairement suspendu les commandes.'],INVALID:[400,'Vérifiez les informations saisies.']};
export async function rpc(name,body){const r=await fetch(process.env.SUPABASE_URL+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:'Bearer '+process.env.SUPABASE_SERVICE_ROLE_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.message||'SERVICE');return data;}
export function prepare(req,res){res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json');if(req.method!=='POST'){res.setHeader('Allow','POST');res.status(405).json({error:'Méthode non autorisée.'});return false;}if(!process.env.SUPABASE_URL||!process.env.SUPABASE_SERVICE_ROLE_KEY){res.status(503).json({error:'La boutique n’est pas connectée.'});return false;}return true;}
export async function limit(req,action,max){const ip=String(req.headers?.['x-vercel-forwarded-for']||req.headers?.['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0].trim();const bucket=action+':'+createHash('sha256').update(ip).digest('hex');if(!await rpc('consume_limit',{bucket,maximum:max}))throw Error('RATE_LIMIT');}
export function body(req){const b=typeof req.body==='string'?JSON.parse(req.body):req.body;if(!b||Array.isArray(b)||typeof b!=='object'||JSON.stringify(b).length>16000)throw Error('INVALID');return b;}
export const phone=v=>typeof v==='string'?v.replace(/\D/g,''):'';
export const text=(v,max,required=true)=>typeof v==='string'&&v.length<=max&&(!required||v.trim().length>0);
export function failure(res,e){const entry=errors[e.message]||[503,'Service indisponible. Réessayez dans un instant.'];return res.status(entry[0]).json({error:entry[1],code:e.message in errors?e.message:'SERVICE'});}
